### ISSUE TITLE
Add vlans field support

### ISSUE THREAD

**Issue by cprivitere** [equinix-labs/terraform-equinix-fabric-connection-metal#3]
If you provide a vlan to the module, it should include the vlans field when setting up the connection so the connection's ports are on the vlan.

[vlans](https://registry.terraform.io/providers/equinix/equinix/latest/docs/resources/equinix_metal_connection#vlans) - (Optional) Only used with shared connection. Vlans to attach. Pass one vlan for Primary/Single connection and two vlans for Redundant connection.

**Comment by ocobleseqx** [comment]
fixed in https://github.com/equinix-labs/terraform-equinix-fabric-connection-metal/pull/4
